name: build site

on:
  push:
    branches: [main]

jobs:
  build:
    uses: grepmorecat/blog-v2/.github/workflow/base.yml@v1


    permissions:
      contents: read

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true


  deploy:
    permissions:
      pages: write
      id-token: write


    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
